### ISSUE TITLE
Initialising SerialTransfer throws TypeError

### ISSUE THREAD

**Issue by robberwick** [PowerBroker2/pySerialTransfer#1]
Using the library under python 3i, when attempting to initialise an instance of the class, `__init__` results in a `TypeError` and the following traceback:

```
Traceback (most recent call last):
  File "./duplex_struct.py", line 5, in <module>
    link = txfer.SerialTransfer('/dev/serial0', baud=57600)
  File "/home/pi/.virtualenvs/tauradigm/lib/python3.5/site-packages/pySerialTransfer/pySerialTransfer.py", line 98, in __init__
    self.txBuff = [' ' for i in (MAX_PACKET_SIZE - 1)]
TypeError: 'int' object is not iterable
```

Updating lines 98 & 99 to the following seems to work for me (assuming that it was the original intention of the code to create a MAX_PACKET_SIZE length array of space characters):

```
        self.txBuff = [' ' for i in range(MAX_PACKET_SIZE)]
        self.rxBuff = [' ' for i in range(MAX_PACKET_SIZE)]
```

**Comment by PowerBroker2** [comment]
Should be fixed in release 1.1.6 - let me know if it didn't
