### ISSUE TITLE
Need byte transfer.

### ISSUE THREAD

**Issue by Menginventor** [PowerBroker2/pySerialTransfer#13]
I dint see byte type in your code. please implement it.
I have more efficiency when working with byte variable instead of send them by int.

**Comment by PowerBroker2** [comment]
If you need to stuff bytes, you can do it manually by accessing the contents of the lists `link.txBuff` and `link.rxBuff`. If your "bytes" are ASCII, you can simply transfer a string using `link.tx_obj()` and `link.rx_obj()`.

Does this help?

**Comment by PowerBroker2** [comment]
Also, you might be able to send a byte array using `link.tx_obj()` and `link.rx_obj()`.

**Comment by Menginventor** [comment]
Actually, I modify you library to my version.
Did you implement 2 byte int for arduino? I see you use 4 byte int in python program

**Comment by PowerBroker2** [comment]
Because Python's int size is 32-bit, integers handled by `link.tx_obj()` and `link.rx_obj()` will be 32-bit. If you really need to send 16-bit ints, you can use `byte_val(val, pos)` to find the two lowest bytes of `val` and stuff them (little-endian) manually into `link.txBuff'.

**Comment by Menginventor** [comment]
Seem like communicate between Arduino and python isn't your primary propose. It okay I totally understand. thank for your clean code I can find where I need to modify for more  convenient.

**Comment by PowerBroker2** [comment]
> Seem like communicate between Arduino and python isn't your primary propose.

Python <--> Arduino communication **was** the entire purpose of creating this Python package...
