### ISSUE TITLE
Type Error: unsupported operand type(s) for += 'int' and 'str'

### ISSUE THREAD

**Issue by 2447SN** [PowerBroker2/pySerialTransfer#15]
I experienced an application crash with the following log. 

Do you have any ideas?

![crash python (2)](https://user-images.githubusercontent.com/62219388/83705994-78b39280-a66a-11ea-8af3-2a1391c8c62f.PNG)

**Comment by PowerBroker2** [comment]
Please post your code in tags

**Comment by PowerBroker2** [comment]
User error - closing ticket
