### ISSUE TITLE
Unable to create SerialConnection to /dev/serial0 & /dev/serial1 on raspberry pi

### ISSUE THREAD

**Issue by robberwick** [PowerBroker2/pySerialTransfer#2]
Under Raspbian on a raspberry pi, there are `serial0` and `serial1` symlinks created in `/dev` to provide access to the underlying UARTS (see [documentation](https://www.raspberrypi.org/documentation/configuration/uart.md)). As it stands, it is not possible to specify either of these symlinks as the port, because they do not contain the string 'tty' - it gets expanded into `/dev/ttyUSBserial0`

**Comment by PowerBroker2** [comment]
hmmm, I'm not very familiar with Linux ports - can you explain each type of port name and maybe a few examples?

**Comment by robberwick** [comment]
under linux the ports can have any name. It's not uncommon for usb serial uarts to be `ttyACM0` for instance. What they do have in common though is that they are all block devices so are all in the `/dev/` directory. I think if we test that the string provided is in that format, then we can just use the string as is, and if not, we take the last part after the `/` (if there is one) and append to `/dev/`.

I'll knock together a PR.

**Comment by PowerBroker2** [comment]
Fixed in release 1.1.7
