### ISSUE TITLE
Portability vs. non-adjustable endianness in Python implementation

### ISSUE THREAD

**Issue by martincizek** [PowerBroker2/pySerialTransfer#25]
To ensure portability, SerialTransfer can either
1. use network byte order on all implementations or
2. let the user choose on all its implementations.

PowerBroker2/SerialTransfer API works with low-level integer types and uses native host byte order. This is OK, as the users in C++ have well-known ways how to ensure endianness compatibility on these low-level integer types, should they need it.

PowerBroker2/pySerialTransfer API works with high-level Python int type and uses struct packing in Python-host-native byte order. This might be an issue, as changing endianness on top of Python int type rapes its semantics and requires a hacky solution.

I'd suggest adding an optional parameter to `tx_obj()` and `rx_obj()` methods, allowing the users to pass byte order to the calls. The value would be according to https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment, native by default.

Does it make sense?

**Comment by PowerBroker2** [comment]
Yes, this makes sense to add once I can get around to it - thanks!

**Comment by martincizek** [comment]
> Yes, this makes sense to add once I can get around to it - thanks!

You're welcome! I've created a PR implementing it, hope it helps. :)
