### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by C-monC** [PowerBroker2/pySerialTransfer#29]
Hi,

Running the example gives me this error. 

`.pio\libdeps\az-delivery-devkit-v4\SerialTransfer\src\SPITransfer.cpp: In member function 'uint8_t SPITransfer::available()':
.pio\libdeps\az-delivery-devkit-v4\SerialTransfer\src\SPITransfer.cpp:111:29: error: 'SPDR' was not declared in this scope
  volatile uint8_t recChar = SPDR;`

Any idea what could cause this? I am using an esp32 with platformio if that matters.

**Comment by PowerBroker2** [comment]
Yeah, this is an issue with how some board cores implemented the SPI API. If you upgrade SerialTransfer.h to its latest version, the error should go away
