### ISSUE TITLE
CRC.calculate() throws TypeError when running example code

### ISSUE THREAD

**Issue by robberwick** [PowerBroker2/pySerialTransfer#3]
Using the example code from readme.md, then following traceback is thrown by the CRC module:

```
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/tauradigm/lib/python3.5/site-packages/pySerialTransfer/CRC.py", line 43, in calculate
    crc = self.cs_table[crc ^ arr[i]]
TypeError: unsupported operand type(s) for ^: 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.virtualenvs/tauradigm/lib/python3.5/site-packages/pySerialTransfer/pySerialTransfer.py", line 228, in send
    found_checksum = self.crc.calculate(self.txBuff, message_len)
  File "/home/pi/.virtualenvs/tauradigm/lib/python3.5/site-packages/pySerialTransfer/CRC.py", line 46, in calculate
    crc = self.cs_table[arr]
TypeError: list indices must be integers or slices, not list
```
I think there's actually two errors in there - the first is on L43 of `calculate()` where an attempt is made to raise `crc` to the power of `arr[i]` - but `arr[i]` is a zero length string (assuming my bodge to address #1 is correct ;-) )

secondly, when that throws a `TypeError`, it falls through to the exception handler and attempts to set `crc` to the value found at index arr of `self.cs_table`, but `arr` is of course an array, so this also fails.

**Comment by PowerBroker2** [comment]
Correct, thank you for bringing this bug to my attention! I went ahead and fixed the library. One note to be aware of is that when specifying a COM port, you should send the port number as a string instead of an int (I already updated the example code).

Let me know if 1.1.6 fixed things for you
