### ISSUE TITLE
Arduino File Example

### ISSUE THREAD

**Issue by kierzenka** [PowerBroker2/pySerialTransfer#43]
Hello,

I am quite new to sending large amounts of data over Serial, but I have found myself in need of doing it for a project. I am using an Ardunio MKR1000 and I am currently trying to get the Loren Ipsum file transfer example working on my computer. There was a small syntax error on line 34 of the rx_file.ino (a missing paren) but otherwise the code is unchanged. 
I am wondering how I can actually see that the file is being transferred since the MKR has only one serial (and software serial does not seem to be supported easily). I tried using the [[uart_rx_file.ino example]](https://github.com/PowerBroker2/SerialTransfer/blob/master/examples/uart_rx_file/uart_rx_file.ino) from the "sister" arduino library but I can't see anything printing and really have no clue if it is working at all. Any guidance would be extremely appreciated!

**Comment by PowerBroker2** [comment]
You have at least two options to verify if your file is being transferred correctly:

1. Save the received file contents to a micro SD card (you will need an SD card adapter to plug into the Arduino)
2. Use a softwareserial port and a UART to USB converter to print debug statements to your computer

There may be other ways, but these are the two to come to mind
