### ISSUE TITLE
pyserialtransfer vs pyserial

### ISSUE THREAD

**Issue by joecorsi** [PowerBroker2/pySerialTransfer#45]
How does this library differ from pyserial? Sorry if this is wrong place to ask, I can't find a more appropriate place!

**Comment by PowerBroker2** [comment]
PySerialTransfer is a wrapper library for pySerial.

PySerial is really just a basic, bare-bones library that allows you to send and receive raw bytes over a USB port with no restrictions. PySerialTransfer, however, is a more advanced library based on pySerial that allows users to send formatted packets of data over USB. These packets of data can be easily formatted, sent, received, and parsed with robust error checking already built into the pySerialTransfer library - features pySerial does not have. PySerialTransfer also has an Arduino compatible C++ library called [SerialTransfer.h](https://github.com/PowerBroker2/SerialTransfer), allowing Python and Arduinos to communicate flawlessly "out of the box" without the programmer needing to create a custom communication protocol (as you would need to do if using pySerial alone).

For more info on what pySerialTransfer can do, take a look at the readme's intro section and the examples provided in this repo.
