### ISSUE TITLE
Check for CRC error

### ISSUE THREAD

**Issue by 8sawte8** [PowerBroker2/pySerialTransfer#63]
Hello,

thank you for this great package!

I wanted to understand your code and manipulated some lines in CRC.py.

But with your example Python script, nothing printed and I didn't get a Python error. After a while, I realized that:

[CRC_ERROR       = 0](https://github.com/PowerBroker2/pySerialTransfer/blob/782c4ab712a530eea797783e01a18941e5227cc3/pySerialTransfer/pySerialTransfer.py#L21)

So I think in the example script it should be:

if link.status <**=** 0:

```
 while not link.available():
                if link.status <= 0:
                    if link.status == txfer.CRC_ERROR:
                        print('ERROR: CRC_ERROR')
                    elif link.status == txfer.PAYLOAD_ERROR:
                        print('ERROR: PAYLOAD_ERROR')
                    elif link.status == txfer.STOP_BYTE_ERROR:
                        print('ERROR: STOP_BYTE_ERROR')
                    else:
                        print('ERROR: {}'.format(link.status))
```
                        
Kind regards,
8sawte8

**Comment by PowerBroker2** [comment]
That's correct, I'll fix at some point. Thanks!
